#!/bin/sh

set -eu

manifest_path="cmd/devcontainer/Cargo.toml"

echo "Running cargo fmt -- --check..."
cargo fmt --manifest-path "$manifest_path" --all -- --check

echo "Running cargo clippy -- -D warnings..."
cargo clippy --manifest-path "$manifest_path" -- -D warnings

echo "Running cargo check..."
cargo check --manifest-path "$manifest_path"
