use std::fs;

use serde_json::{Map, Value};

use super::materialize::{
    alternate_feature_option_values, feature_installation, feature_option_values,
    scenario_base_image, scenario_feature_installations, unique_feature_test_dir,
};
use super::{
    BaseImageSource, FeatureInstallation, FeatureInstallationSource, FeatureTestCase,
    FeatureTestExecution, FeatureTestOptions, PreparedFeatureTestCase, FEATURE_TEST_LIBRARY_SCRIPT,
    FEATURE_TEST_LIBRARY_SCRIPT_NAME,
};
use crate::commands::common;

pub(super) fn discover_feature_test_cases(args: &[String]) -> Result<Vec<FeatureTestCase>, String> {
    let project_folder = common::parse_option_value(args, "--project-folder")
        .or_else(|| common::parse_option_value(args, "--projectFolder"))
        .or_else(|| args.iter().rev().find(|arg| !arg.starts_with('-')).cloned())
        .ok_or_else(|| "features test requires a project folder".to_string())?;
    let filter = common::parse_option_value(args, "--filter");
    let feature_filter = common::parse_option_value(args, "-f")
        .or_else(|| common::parse_option_value(args, "--features"));
    let skip_scenarios = common::has_flag(args, "--skip-scenarios");
    let global_scenarios_only = common::has_flag(args, "--global-scenarios-only");
    let skip_autogenerated = common::has_flag(args, "--skip-autogenerated");
    let skip_duplicated = common::has_flag(args, "--skip-duplicated");
    let test_root = std::path::Path::new(&project_folder).join("test");
    let mut cases = Vec::new();

    if let Ok(entries) = fs::read_dir(&test_root) {
        for entry in entries {
            let entry = entry.map_err(|error| error.to_string())?;
            if !entry.path().is_dir() {
                continue;
            }
            let name = entry.file_name().to_string_lossy().to_string();
            if name == "_global" {
                if feature_filter.is_none() && !skip_scenarios {
                    cases.extend(load_named_scenarios(&entry.path())?);
                }
                continue;
            }
            if global_scenarios_only {
                continue;
            }
            if feature_filter
                .as_deref()
                .is_some_and(|value| value != name.as_str())
            {
                continue;
            }
            if entry.path().join("test.sh").is_file() && !skip_autogenerated {
                cases.push(FeatureTestCase {
                    name: name.clone(),
                    script_path: entry.path().join("test.sh"),
                    execution: FeatureTestExecution::Autogenerated {
                        feature: name.clone(),
                    },
                });
            }
            if entry.path().join("duplicate.sh").is_file() && !skip_duplicated {
                cases.push(FeatureTestCase {
                    name: format!("{name} executed twice with randomized options"),
                    script_path: entry.path().join("duplicate.sh"),
                    execution: FeatureTestExecution::Duplicate {
                        feature: name.clone(),
                    },
                });
            }
            if !skip_scenarios {
                cases.extend(load_named_scenarios(&entry.path())?);
            }
        }
    }

    cases.sort_by(|left, right| left.name.cmp(&right.name));
    cases.dedup_by(|left, right| left.name == right.name);
    if let Some(filter) = filter {
        cases.retain(|scenario| scenario.name.contains(&filter));
    }
    Ok(cases)
}

fn load_named_scenarios(test_dir: &std::path::Path) -> Result<Vec<FeatureTestCase>, String> {
    let scenarios_path = test_dir.join("scenarios.json");
    if !scenarios_path.is_file() {
        return Ok(Vec::new());
    }
    let raw = fs::read_to_string(scenarios_path).map_err(|error| error.to_string())?;
    let parsed = crate::config::parse_jsonc_value(&raw)?;
    parsed
        .as_object()
        .map(|entries| {
            entries
                .iter()
                .map(|(name, config)| {
                    let script_path = test_dir.join(format!("{name}.sh"));
                    if !script_path.is_file() {
                        return Err(format!(
                            "No scenario test script found at path '{}'",
                            script_path.display()
                        ));
                    }
                    Ok(FeatureTestCase {
                        name: name.clone(),
                        script_path,
                        execution: FeatureTestExecution::Scenario {
                            scenario_dir: name.clone(),
                            config: config.clone(),
                        },
                    })
                })
                .collect()
        })
        .unwrap_or_else(|| Ok(Vec::new()))
}

pub(super) fn prepare_feature_test_case(
    options: &FeatureTestOptions,
    case: &FeatureTestCase,
) -> Result<PreparedFeatureTestCase, String> {
    let workspace_dir = unique_feature_test_dir();
    fs::create_dir_all(&workspace_dir).map_err(|error| error.to_string())?;
    let test_dir = case
        .script_path
        .parent()
        .ok_or_else(|| format!("Invalid test script path: {}", case.script_path.display()))?;
    common::copy_directory_recursive(test_dir, &workspace_dir)?;
    fs::write(
        workspace_dir.join(FEATURE_TEST_LIBRARY_SCRIPT_NAME),
        FEATURE_TEST_LIBRARY_SCRIPT,
    )
    .map_err(|error| error.to_string())?;
    let script_name = case
        .script_path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| format!("Invalid test script path: {}", case.script_path.display()))?
        .to_string();
    let build_context_dir = workspace_dir.join(".feature-test-build");
    fs::create_dir_all(&build_context_dir).map_err(|error| error.to_string())?;

    let (base_image, feature_installations, exec_env) = match &case.execution {
        FeatureTestExecution::Autogenerated { feature } => (
            BaseImageSource::Image(options.base_image.clone()),
            vec![feature_installation(
                &options.project_folder.join("src").join(feature),
                &Value::Object(Map::new()),
            )?],
            Vec::new(),
        ),
        FeatureTestExecution::Scenario {
            scenario_dir,
            config,
        } => (
            scenario_base_image(options, scenario_dir, config, &workspace_dir)?,
            scenario_feature_installations(
                &options.project_folder,
                case.script_path
                    .parent()
                    .and_then(|path| path.file_name())
                    .and_then(|value| value.to_str())
                    .filter(|value| *value != "_global"),
                config,
            )?,
            Vec::new(),
        ),
        FeatureTestExecution::Duplicate { feature } => {
            let feature_dir = options.project_folder.join("src").join(feature);
            let default_options = feature_option_values(&feature_dir, &Value::Object(Map::new()))?;
            let alternate_options = alternate_feature_option_values(&feature_dir)?;
            let mut exec_env = alternate_options.clone();
            exec_env.extend(
                default_options
                    .iter()
                    .map(|(key, value)| (format!("{key}__DEFAULT"), value.clone())),
            );
            (
                BaseImageSource::Image(options.base_image.clone()),
                vec![
                    FeatureInstallation {
                        source: FeatureInstallationSource::Local(feature_dir.clone()),
                        env: alternate_options.clone(),
                    },
                    FeatureInstallation {
                        source: FeatureInstallationSource::Local(feature_dir),
                        env: default_options,
                    },
                ],
                exec_env,
            )
        }
    };

    Ok(PreparedFeatureTestCase {
        name: case.name.clone(),
        workspace_dir,
        build_context_dir,
        base_image,
        script_name,
        feature_installations,
        exec_env,
        remote_user: options.remote_user.clone(),
    })
}
